name: Create Pull Request

on:
  push:
    branches:
      - dev1

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print debug information
        run: |
          echo "Repository is: ${{ github.repository }} branch is dev1"
          echo "Event Commit Message: ${{ github.event.head_commit.message }}"

      - name: Create pull request
        run: |
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"${{ github.event.head_commit.message }}\", \"head\": \"dev1\", \"base\": \"develop\"}"
